version: '3.1'

services:
    app:
        hostname: kitchenwizard
        image: kitchenwizard
        restart: always
        ports:
            -   "8000:80"
        networks:
           # - web
            - host
        labels:
            - "traefik.http.routers.romainalcon.rule=Host(`new-portfolio.romainalcon.me`)"
            - "traefik.http.routers.romainalcon.tls=true"
            - "traefik.http.routers.romainalcon.tls.certresolver=lets-encrypt"
            - "traefik.http.routers.romainalcon.entrypoints=websecure"
            - "traefik.http.services.romainalcon.loadbalancer.server.port=8000"
        volumes:
            - ./storage:/app/storage
            - ./.env:/app/.env
#        depends_on:
#            common-postgres:
#                condition: service_healthy
networks:
#    web:
#        external: true
    host:
        driver: bridge
