version: '3.1'

services:
    app:
        hostname: kitchenwizard
        image: kitchenwizard
        restart: always
        ports:
            -   "8000:8000"
        networks:
           # - web
            - host
        labels:
            - "traefik.http.routers.kitchenwizard.rule=Host(`miammmm.fr`)"
            - "traefik.http.routers.kitchenwizard.tls=true"
            - "traefik.http.routers.kitchenwizard.tls.certresolver=lets-encrypt"
            - "traefik.http.routers.kitchenwizard.entrypoints=websecure"
            - "traefik.http.services.kitchenwizard.loadbalancer.server.port=8000"
        volumes:
            - ./:/app
           # - ./storage:/app/storage
           # - ./.env:/app/.env
#        depends_on:
#            common-postgres:
#                condition: service_healthy
networks:
#    web:
#        external: true
    host:
        driver: bridge
