services:
    app:
        hostname: kitchenwizard
        image: kitchenwizard
        restart: unless-stopped
        network_mode: host
        ports:
            -   "8000:8000"
#        networks:
#           # - web
#            - host

        volumes:
            - ./:/app
           # - ./storage:/app/storage
           # - ./.env:/app/.env
#        depends_on:
#            common-postgres:
#                condition: service_healthy
networks:
#    web:
#        external: true
    host:
        driver: bridge
