services:
    app:
        #hostname: kicthenwizard
        image: kicthenwizard
        restart: unless-stopped
        network_mode: host
        ports:
            -   "8000:8000"
        volumes:
            - ./:/app
            - ./storage:/app/storage
            #- ./.env:/app/.env
#        networks:
#           # - web
#            - host
#        depends_on:
#            common-postgres:
#                condition: service_healthy
networks:
#    web:
#        external: true
    host:
        driver: bridge
